### ISSUE TITLE
CDA2CCD to FHIR DateTime bug in Runtime - 2 errors

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#143]
Maps and messages included in zip file.
[dateTimeExecutionErrorFiles.zip](https://github.com/MDMI/mdmiecore/files/2125067/dateTimeExecutionErrorFiles.zip)

The current runtime is spitting two very different types of errors in DateTime datatype processing.

1.  The Day in a YYYYmmDD format is incorrect if dateTime processed. The date comes out as a random 3 numeral string. Example from source message C-CDA_R2_CCD.xml:
<low value="20130703" />
Target message:
<onsetDateTime value="2013-07-184"/>

2. datatypeMapping does not execute if formatting different from YYYYmmdd even though dataType mapping should support. Example from source message Giovannni.....xml provided by Gary Duff:

source message:
<low value="20110811204117"/>
datatype mapping javascript:
 function mapDateTimeToFHIR_date(source,target) {
 target.setValue('value', org.mdmi.core.engine.javascript.Utils.FormatDate("yyyyMMddHHmmssZ","YYYY-MM-DD'T'hh:mm:ss",source.getValue()));
}
trace error:
[TRACE] convert business element ProblemConditionObservationOnsetDateTime
[TRACE] Executing Method mapTSToDateTime
[TRACE] Executing Method mapDateTimeToFHIR_dateTime
[ERROR] Failed executing Executing mapDateTimeToFHIR_dateTime := Cannot format given Object as a Date
[ERROR] Cannot format given Object as a Date
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.text.DateFormat.format(Unknown Source)
	at java.text.Format.format(Unknown Source)
	at org.mdmi.core.engine.javascript.Utils.FormatDate(Utils.java:92)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$19013AA$\^eval\_.mapDateTimeToFHIR_dateTime(<eval>:659)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:641)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.mdmi.core.engine.DatamapInterpreter.execute(DatamapInterpreter.java:251)
	at org.mdmi.core.engine.ConversionImpl.execMapFromMDMI(ConversionImpl.java:368)
	at org.mdmi.core.engine.ConversionImpl.convert(ConversionImpl.java:165)
	at org.mdmi.core.engine.MdmiUow.processConversions(MdmiUow.java:513)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:174)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:79)
	at org.mdmi.core.Mdmi.exec(Mdmi.java:382)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:276)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:97)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:133)
[ERROR] DATATYPE MISMATCH FOR BUSINESS ELEMENT ProblemConditionObservationOnsetDateTime

**Comment by swmuir** [comment]
Fixed the issue with [ERROR] Cannot format given Object as a Date

**Comment by mryanlord** [comment]
Got it. Have you looked at at the first issue? I still see that . Did you notice it in your tests?

**Comment by swmuir** [comment]
yes - i have a fix in the works

**Comment by swmuir** [comment]
Pushed a fix - do a restart and check for updates

**Comment by mryanlord** [comment]
resolved
